version: '2'
checks:
  argument-count:
    enabled: true #was false  handled by PMD
  complex-logic:
    enabled: true
  file-lines:
    enabled: true # was false handled by PMD
  method-complexity:
    enabled: true # was false  handled by PMD
  method-count:
    enabled: true # was false  Handled by PMD
  method-lines:
    enabled: true # was false  Handled by PMD
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true # was false  Handled by PMD
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
#  checkstyle:
#    enabled: true
#    config:
#      file: 'config/vogle-checkstyle.xml'
#  pmd:
#    enabled: true
#    config:
#      file: 'config/vogle-ruleset-6.7.x.xml'
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
    checks:
      squid:S1948:
        enabled: false
exclude_patterns:
  - 'config/'
  - '**/dist/'
  - '**/build/'
  - '**/test/'
  - '**/integTest/'
  - '**/*.md'
