include:
  - template: Code-Quality.gitlab-ci.yml

image: maven:latest

stages:
    - build
    - test

build-java-project:
    stage: build
    script: $MAVEN_HOME/bin/mvn package

code_quality:
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
