version: "3.5"

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8011:8080"
  web:
    image: maven:3.6.3-jdk-8
    command: mvn spring-boot:run
    ports:
      - "8010:8080"
    volumes:
      - .:/usr/src/mymaven:rw
    working_dir: /usr/src/mymaven
    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://db:3306/data_base",
        "spring.datasource.username":"root",
        "spring.datasource.password":"example"
      }'